create database CrimeRecords;
use CrimeRecords;

create table Admin(
ADMIN_NAME VARCHAR(20) primary KEY,
ADMIN_ID INT(4) primary KEY NOT NULL auto_increment DEFAULT 1000,
ADMIN_PASSWORD varchar(10),
ADMIN_DESGINATION VARCHAR (25),
ADMIN_EMAIL VARCHAR(20)
);
SELECT *FROM ADMIN;
INSERT INTO ADMIN( ADMIN_NAME,ADMIN_PASSWORD ,ADMIN_DESGINATION,ADMIN_EMAIL)VALUES('SHUBHAM CHOUBE','SHUBHAM@90','PSI','shubham@gmail.com');
INSERT INTO ADMIN( ADMIN_NAME,ADMIN_PASSWORD ,ADMIN_DESGINATION,ADMIN_EMAIL) VALUES('ABHISHEK AYARE','ABHI@91','DIG','abhishek@gmail.com');
INSERT INTO ADMIN( ADMIN_NAME,ADMIN_PASSWORD ,ADMIN_DESGINATION,ADMIN_EMAIL) VALUES('RAJESH AGRAWAL','RAJESH@92','ACP','Rajesh@gmail.com');
INSERT INTO ADMIN( ADMIN_NAME,ADMIN_PASSWORD ,ADMIN_DESGINATION,ADMIN_EMAIL) VALUES('MAHESH TIWARI','MAHESH@93','ACP','shailesh@gmail.com');
INSERT INTO ADMIN( ADMIN_NAME,ADMIN_PASSWORD ,ADMIN_DESGINATION,ADMIN_EMAIL )VALUES('ABHAY TIWARI','ABHAY@90','SP','Abhay@gmail.com');
INSERT INTO ADMIN( ADMIN_NAME,ADMIN_PASSWORD ,ADMIN_DESGINATION,ADMIN_EMAIL) VALUES('RAJAN MISHRA','RAJAN@90','PSI','Rajendra@gmail.com');
INSERT INTO ADMIN( ADMIN_NAME,ADMIN_PASSWORD ,ADMIN_DESGINATION,ADMIN_EMAIL) VALUES('SURESH JAISWAL','SURESH@98','SP','Suresh@gmail.com');
INSERT INTO ADMIN( ADMIN_NAME,ADMIN_PASSWORD ,ADMIN_DESGINATION,ADMIN_EMAIL) VALUES('ARVIND KHORIA','ARVIND@90','INSPECTOR','arvind21@gmail.com');
INSERT INTO ADMIN( ADMIN_NAME,ADMIN_PASSWORD ,ADMIN_DESGINATION,ADMIN_EMAIL) VALUES('MANISH SHARMA','MANISH@91','PSI','Rajendra@gmail.com');
INSERT INTO ADMIN( ADMIN_NAME,ADMIN_PASSWORD ,ADMIN_DESGINATION,ADMIN_EMAIL) VALUES('ANKIT SARAF','ANKIT@90','SUB-INSPECTOR','Rajendra@gmail.com');
ALTER TABLE ADMIN ADD COLUMN ACCUSED_NAME varchar(20);
ALTER TABLE ADMIN ADD COLUMN COMPLAINANT_NAME varchar(20);
DELETE FROM ADMIN WHERE ADMIN_NAME='SHUBHAM CHOUBE';
ROLLBACK;
SET AUTOCOMMIT=0;
SELECT *FROM ADMIN;
DESC ADMIN;
-- delimiter $$
/* CREATE PROCEDURE spAdminDtl(in AD_NAME varchar(20),AD_ID INT(4),AD_PASSWORD VARCHAR(10),AD_DESGINATION VARCHAR(25),AD_EMAIL varchar(20))
begin

end $$
call spAdminDtl();
call spAdminDtl();
*/




create table accused(
ACCUSED_CASE_NO INT(5) primary KEY,
ACCUSED_NAME VARCHAR(20),
ACCUSED_SECTION INT(15),
ACCUSED_ADRESS varchar(30),
ACCUSED_AGE INT(2),
CASE_STATUS VARCHAR(15),
INCHARGE_OFFICER_ID int(4),
constraint foreign key (INCHARGE_OFFICER_ID) references ADMIN(ADMIN_ID)
);
DESC ACCUSED;
alter table accused add column NEXT_DATE date;
ALTER TABLE ACCUSED modify COLUMN ACCUSED_CASE_NO varchar(15);
-- ACCUSED RECORDS
INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('111/2001','MANOJ THAKUR',420,'THANE',35,'PENDING',1003);
 UPDATE ACCUSED SET CASE_STATUS='DISCHARGED' WHERE ACCUSED_NAME='MANOJ THAKUR';
 SELECT * FROM ACCUSED;
 SHOW procedure status;
 CALL sp_cr_CaseStatus('111/2001');
  CALL sp_cr_CaseStatus('113/2020');
INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('112/2020','MITESH TIBDEWAL',302,'KURLA',31,'DISCHARGED',1005,null);

INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('113/2020','PAWAN MISHRA',297,'THANE',26,'PENDING',1004,str_to_date('25-Oct-2020','%d-%M-%Y'));
 INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('114/2020','SANJAY GOYAL',255,'BANDRA',32,'DISCHARGED',1008,null);
 INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('115/2020','BHASKAR SINGH',307,'SANTA CRUZ',26,'PENDING',1010,str_to_date('15-Nov-2020','%d-%M-%Y'));
 INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('116/2020','AMOL RATHOR',201,'PANVEL',45,'DISCHARGED',1007,nULL);
 INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('117/2020','ATAL PANDE',149,'PANVEL',43,'PENDING',1007,str_to_date('21-Aug-2020','%d-%M-%Y'));
  INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('176/2013','KIRTI PATEL',392,'MULUND',36,'PENDING',1005,str_to_date('30-Nov-2020','%d-%M-%Y'));
  INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('60/2016','SUFIYAN SHIEKH',416,'DADAR',42,'PENDING',1007,str_to_date('05-Dec-2020','%d-%M-%Y'));
  INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('160/2016','RIYA RANE',415,'BHANDOOP',27,'PENDING',1004,str_to_date('30-Nov-2020','%d-%M-%Y'));
  INSERT INTO ACCUSED (ACCUSED_CASE_NO,ACCUSED_NAME,ACCUSED_SECTION,ACCUSED_ADRESS,ACCUSED_AGE,CASE_STATUS,INCHARGE_OFFICER_ID,NEXT_DATE)
 VALUES ('140/2015','PRIYA MEHTA',420,'VIKROLI',47,'DISCHARGED',1004,null);


-- ---------------------------------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------
create table Complainant(
COMPLAINANT_CASE_NO INT(5) primary KEY,
COMPLAINANT_NAME VARCHAR(20),
CASE_STATUS VARCHAR(15),
INCHARGE_OFFICER_ID int(4),
FOREIGN KEY(INCHARGE_OFFICER_ID ) references ADMIN(ADMIN_ID)
);
DESC COMPLAINANT;
select * from COMPLAINANT;
show tables;
select admin.*,accused.* from  admin inner join accused on admin.admin_id=accused.incharge_officer_id 
inner join complainant on accused.incharge_officer_id=complainant.incharge_officer_id;

ALTER TABLE COMPLAINANT modify COLUMN COMPLAINANT_CASE_NO varchar(15);

insert into COMPLAINANT values ('111/2001','SUHAS PATIL','PENDING',1003);
insert into COMPLAINANT values ('112/2020','VIKAS PANDE','FINISHED',1005);
insert into COMPLAINANT values ('113/2020','GOPAL JOSHI','PENDING',1004);
insert into COMPLAINANT values ('114/2020','AKSHAY SHARMA','PENDING',1008);
insert into COMPLAINANT values ('115/2020','RAJAT THAKKAR','PENDING',1010);
insert into COMPLAINANT values ('116/2020','VILAS KALE','FINISHED',1007);
insert into COMPLAINANT values ('176/2013','SURESH PATEL','PENDING',1005);
insert into COMPLAINANT values ('60/2016','AMJAD ALI','PENDING',1007);
insert into COMPLAINANT values ('160/2016','RAVI KALE','PENDING',1004);
insert into COMPLAINANT values ('140/2015','HARSHAD MEHTA','DISCHARGED',1004);


-- CALL sp_cr_AdminAlottedCase('SURESH JAISWAL');
CALL sp_cr_join;
CALL sp_cr_AdminStatus(1004);
call sp_cr_AccusedInfo('140/2015');


UPDATE ACCUSED SET NEXT_DATE=str_to_date('15-Nov-2020','%d-%M-%Y') WHERE ACCUSED_CASE_NO='PAWAN MISHRA';